export interface Card {
    id?: number,
    veicolo?: number,
    proprietario?: number,
    agente?: number,
    dealer?: number,
    venditore?: number,
    data_inserimento?: string,
    data_attivazione?: string,
    data_scadenza?: string,
    id_proforma?: number,
    id_proforma_restituzione?: number,
    tipo_card?: number,
    restituzione?: number,
    stato?: boolean,
    is_deleted?: boolean,
    is_imported?: boolean,
    sigla?: string,
    dealer_nome?: string,
    clienti?: string,
    targa?: string,
    marca?: string
}

export const CardSearchKeys = [
    'id',
    'veicolo',
    'proprietario',
    'agente',
    'dealer',
    'venditore',
    'data_inserimento',
    'data_attivazione',
    'data_scadenza',
    'id_proforma',
    'id_proforma_restituzione',
    'tipo_card',
    'restituzione',
    'stato',
    'sigla',
    'dealer_nome',
    'clienti',
    'targa',
    'marca'
]